# --- Main Colors ---
background            #0f1417
foreground            #dfe3e7
cursor                #dfe3e7
cursor_text_color     #0f1417

selection_background  #354a53
selection_foreground  #d0e6f2

url_color             #c6c2ea

# --- ANSI Colors ---
color0                #0f1417
color1                #ffb4ab
color2                #c6c2ea
color3                #b4cad6
color4                #8bd0ef
color5                #c6c2ea
color6                #b4cad6
color7                #dfe3e7

color8                #40484c
color9                #93000a
color10               #454364
color11               #354a53
color12               #004d64
color13               #354a53
color14               #454364
color15               #c0c8cd
