include colors.conf

font_family           JetBrainsMono Nerd Font Mono
font_size             11

disable_ligatures     no
enable_audio_bell     no

shell                 /usr/bin/fish
shell_integration     disabled

url_style             curly

remember_window_size  no
window_padding_width  20
cursor_blink_interval 0

background_opacity 0.8
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

sync_to_monitor no

repaint_delay 8
input_delay 3

cursor_trail 10
cursor_trail_start_threshold 0
cursro_trail_decay 0.01 0.05
cursor_shape block
cursor_blink true

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
