require("modules.monitors")
require("modules.keybinds")
require("modules.autostarts")
require("modules.env")
require("modules.decorations")
require("modules.layout")
require("modules.misc")
require("modules.input")
require("modules.windowsrules")

